--- LOCAL SERVER
CREATE TABLE `ADMINS` (
            `USER` CHAR(256) PRIMARY KEY NOT NULL,
            `PASSWORD` CHAR(512) NOT NULL
);

CREATE TABLE `USERS` (
            `ID` INT PRIMARY KEY NOT NULL,
            `PASSWORD` CHAR(512) NOT NULL,
            `ROOM` INT NOT NULL
);

CREATE TABLE `ADMIN_SESSION` (
            `ID` CHAR(16) PRIMARY KEY NOT NULL,
            `USER` CHAR(256) NOT NULL,
            `LOGIN_DATE` DATETIME NOT NULL,
            `EXPIRE_DATE` DATETIME NOT NULL
);

CREATE TABLE `USER_SESSION` (
            `ID` CHAR(16) PRIMARY KEY NOT NULL,
            `USER` INTEGER NOT NULL,
            `LOGIN_DATE` DATETIME NOT NULL,
            `VALID` BOOLEAN NOT NULL DEFAULT 1
);

--- MAIN SERVER
CREATE TABLE `USERS` (
            `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
            `PASSWORD` CHAR(512) NOT NULL,
            `LIGHT` INT NOT NULL,
            `OFFICE` INT NOT NULL,
            `ROOM` INT NOT NULL
);

CREATE TABLE `ACTIVITY` (
            `USER` INT NOT NULL,
            `OFFICE` INT NOT NULL,
            `DATETIME` DATETIME NOT NULL,
            `TYPE` CHAR(512) NOT NULL
);

CREATE TABLE `OFFICE` (
            `ID` INT PRIMARY KEY NOT NULL,
            `NAME` TEXT NOT NULL,
            `API_KEY` VARCHAR(512) NOT NULL UNIQUE       
);


